Mag 23
withreach/magento-plugin pull request #24
Opened 2019-11-25 22:06 UTC by cstech

Made country submit to the API without a region

2019-11-25 23:58 UTC, lizzynibali commented on Model/DutyCalculator.php
> -            if (empty($address->getCountryId()) || empty($address->getRegionCode())) {
I don't understand how this works, if the country is empty then we got the duties and taxes? And this is an OR statement, so it should have worked before right?

2019-11-25 23:58 UTC, lizzyWithReach requested changes
I'm just not sure why this code change works, if you could provide more context that would be great. I'm guessing I'm missing something

2019-11-26 16:56 UTC, cstech commented
Going to remove block of code

2019-11-26 16:56 UTC, closed without merging

2019-11-26 16:57 UTC, lizzynibali commented on Model/DutyCalculator.php
> -            if (empty($address->getCountryId()) || empty($address->getRegionCode())) {
Clarified with Ervin, if the country is empty (which it won't ever be) then the duties would be reset to 0 and we would never call DHL. That's what this block is doing